FROM tiangolo/uvicorn-gunicorn-fastapi:python3.11

WORKDIR /app/

COPY requirements.txt requirements-dev.txt ./

RUN pip install -r requirements-dev.txt

ENV PORT 8000
ENV DOCKER=true

COPY main.py index.html ./
COPY celery_app ./celery_app/